[package]
name = "rsget"
version = "1.0.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "Apache-2.0"
edition = "2018"
readme = "README.md"

[dependencies]
reqwest = { version = "0.10.0", default-features = false, features = ["blocking"] }
failure = "0.1.6"
structopt = "0.3.7"
indicatif = "0.13.0"
exitfailure = "0.5.1"
